
// src/models/AppSettings.model.ts
import mongoose, { Schema, Document, models, Model } from 'mongoose';
import type { AppSettings, SpecificDayRule } from '@/lib/types';

const SpecificDayRuleSchema: Schema<SpecificDayRule> = new Schema({
  id: { type: String, required: false }, // Make id optional for subdocuments if not always present
  date: { type: String, required: true }, 
  isOff: { type: Boolean },
  workingHours: [{ type: String }], 
  numberOfStaff: { type: Number },
  serviceDurationMinutes: { type: Number },
}, { _id: true }); // _id will be generated by default, or use id from type if provided

export interface IAppSettings extends Document, Omit<AppSettings, 'id' | 'specificDayRules'> {
  specificDayRules?: mongoose.Types.DocumentArray<SpecificDayRule>; 
}

const AppSettingsSchema: Schema<IAppSettings> = new Schema({
  greetingMessage: { type: String, default: 'Tôi là trợ lý AI của bạn. Tôi có thể giúp gì cho bạn hôm nay? Bạn có thể hỏi về dịch vụ hoặc đặt lịch hẹn.' },
  greetingMessageNewCustomer: { type: String },
  greetingMessageReturningCustomer: { type: String },
  suggestedQuestions: [{ type: String, default: ['Các dịch vụ của bạn?', 'Làm thế nào để đặt lịch hẹn?'] }],
  brandName: { type: String, default: 'AetherChat' },
  logoUrl: { type: String }, 
  logoDataUri: { type: String }, 
  footerText: { type: String, default: `© ${new Date().getFullYear()} AetherChat. Đã đăng ký Bản quyền.` },
  metaTitle: { type: String, default: 'AetherChat - Live Chat Thông Minh' },
  metaDescription: { type: String, default: 'Live chat tích hợp AI cho giao tiếp khách hàng liền mạch.' },
  metaKeywords: [{type: String}],
  openGraphImageUrl: {type: String},
  robotsTxtContent: {type: String},
  sitemapXmlContent: {type: String},

  numberOfStaff: { type: Number, default: 1, min: 0 },
  defaultServiceDurationMinutes: { type: Number, default: 60, min: 5 },
  workingHours: [{ type: String, default: ["09:00", "10:00", "11:00", "13:00", "14:00", "15:00", "16:00", "17:00"] }], 
  weeklyOffDays: [{ type: Number, min: 0, max: 6 }], 
  oneTimeOffDates: [{ type: String }], 
  specificDayRules: [SpecificDayRuleSchema],

  // Out-of-Office Settings
  outOfOfficeResponseEnabled: { type: Boolean, default: false },
  outOfOfficeMessage: { type: String, default: 'Cảm ơn bạn đã liên hệ! Hiện tại chúng tôi đang ngoài giờ làm việc. Vui lòng để lại lời nhắn và chúng tôi sẽ phản hồi sớm nhất có thể.' },
  officeHoursStart: { type: String, default: "09:00" }, // e.g., "09:00"
  officeHoursEnd: { type: String, default: "17:00" },   // e.g., "17:00"
  officeDays: [{ type: Number, default: [1,2,3,4,5] }], // [1,2,3,4,5] for Mon-Fri

}, { timestamps: true, versionKey: false });

const AppSettingsModel = models.AppSettings as Model<IAppSettings> || mongoose.model<IAppSettings>('AppSettings', AppSettingsSchema);

export default AppSettingsModel;
